{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "19c9ee44",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "4bee7153",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv(\"/home/mi/zpz/xuexi/小型CSV数据/rygh/Advertising.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "ebe694ee",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>TV</th>\n",
       "      <th>radio</th>\n",
       "      <th>newspaper</th>\n",
       "      <th>sales</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>230.1</td>\n",
       "      <td>37.8</td>\n",
       "      <td>69.2</td>\n",
       "      <td>22.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>44.5</td>\n",
       "      <td>39.3</td>\n",
       "      <td>45.1</td>\n",
       "      <td>10.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>17.2</td>\n",
       "      <td>45.9</td>\n",
       "      <td>69.3</td>\n",
       "      <td>9.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>151.5</td>\n",
       "      <td>41.3</td>\n",
       "      <td>58.5</td>\n",
       "      <td>18.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>180.8</td>\n",
       "      <td>10.8</td>\n",
       "      <td>58.4</td>\n",
       "      <td>12.9</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Unnamed: 0     TV  radio  newspaper  sales\n",
       "0           1  230.1   37.8       69.2   22.1\n",
       "1           2   44.5   39.3       45.1   10.4\n",
       "2           3   17.2   45.9       69.3    9.3\n",
       "3           4  151.5   41.3       58.5   18.5\n",
       "4           5  180.8   10.8       58.4   12.9"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "e02f73ec",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.collections.PathCollection at 0x7f8fb45c5150>"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXAAAAD4CAYAAAD1jb0+AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAjlklEQVR4nO2df5Af5X3f3587fYE7SDkRVAbOCKmtBwassRTd2HTU6ViyGxJj7AtkIIyTkKmn+idtjcrQnFtPwVM6XENsnE46npLgGicMFbHomZhMiIPUMmZq0pMlLDCidgIYzjLIRecf6Cin06d/fL8r9vb22X1299nd59nv+zWj0X339r777He/+36efX8+z+cRVQUhhJDwGGm7AYQQQspBASeEkEChgBNCSKBQwAkhJFAo4IQQEijrmjzYhRdeqJs2bWrykIQQEjwHDx78kapuSG5vVMA3bdqE+fn5Jg9JCCHBIyIvp22nhUIIIYFCASeEkEChgBNCSKBQwAkhJFAo4IQQEiiNZqGQ4WLu0ALuefwF/GBxCZdMjOH2ay7H9LbJtptFSGeggJNamDu0gE89cgRLyysAgIXFJXzqkSMAQBEnxBG0UEgt3PP4C2fEO2JpeQX3PP5CSy0ipHtQwEkt/GBxqdB2QkhxKOCkFi6ZGCu0nRBSHAo4qYXbr7kcY73RVdvGeqO4/ZrLW2oRId2DQUxSC1Ggklko1WAmD8mCAk5qY3rbJMWmAszkIXnQQiHEU5jJQ/KggBPiKczkIXlQwAnxFGbykDwo4IR4CjN5SB4MYhJSM2UzSZjJQ/LopIAz9cp/XF0j36911UwSZvKQLDpnoUQ3zMLiEhTv3DBzhxbabhoZ4OoahXCtmUlC6qRzAs4bxn9cXaMQrjUzSUid5Aq4iFwqIgdE5Dsi8pyIfHKw/U4RWRCRw4N/H66/ufnwhvEfV9cohGvNTBJSJzYj8FMAblPVKwFcDeC3ReTKwe/uVdWtg39/XlsrC8Abxn9cXaMQrjUzSUid5Aq4qh5T1W8Nfv4pgOcBeBNVmTu0gB2z+7F55jHsmN2PnVds4A3jOa5ELQRxnN42ibuv34LJiTEIgMmJMdx9/RYGJokTRFXtdxbZBOBJAO8B8K8A/BaAnwCYR3+UfiLlb3YD2A0AGzdu3P7yyy9XbnREMsIP9G/gG7ZP4sDR495mJpDhyUIhxAUiclBVp9ZstxVwETkPwP8E8B9U9RERuQjAjwAogH8P4GJV/adZ7zE1NaXz8/OFG29ix+x+LKT4nZMTY3hqZpez45BuQdEnoWEScKs8cBHpAdgH4EFVfQQAVPW12O//EMDXHLXVmhCCWMQvWOGPdAmbLBQBcD+A51X1c7HtF8d2+xUAz7pvXjYhBLGIH0Sxklv3HvY+9ZAQW2yyUHYA+A0AuxIpg78rIkdE5NsAdgLYU2dD0wghiEXaJz7hxwSf2kiI5FooqvoNAJLyq9bTBlkrgtiQNuEnCZ/aSIgEXwuFtSKaJcQAYN7omk9t3SLE72hZghdw0hyhBgAvmRgz2ieTOTf4MIlBFwj1O1qWztVCIfURQu2RNEyxks/ftBVPzezKFG/fi2WR1YT6HS0LBZxYE2raZtnZkMMmBl0g1O9oWWihEGtMVkQIAcAysZJhE4MuEPJ3tAwcgTdAsl5LqI/gw5a2yXkG4TFs31EKeM10yUcdtsJMwyYGXWDYvqOFillVxXUtlBBgvZawYRYK8YFKtVBIeeijhg3nGRCfoYVSMya/VIGg/fA4XfH4CQkNCnjNpPmoESH74RFd8vgJCQ0KeM3EgypphJ5X7GOuNJ8IyLBAD7wBIh9188xjSAsZV/HD2w6y+ebxD9tUajLcUMAbxPUkAx/EyreJE1lPBL4KeF4n3HYnTfyFFkqDuM4r9sG+8C1X2rcngjzyYgiMMZAsKOAN4nqSgQ9i5dvEidBmT+Z1wj500sRfaKE0jE1ese0js0v7ospjuk+50rdfc/kqWwnwe/ZkXifsQydN/IUjcM8o8sjsyr7o0mO6b08EeeQ9MYT2REGahSNwzygShCu7pFxytH3y7VPBBf6y8OmJII+8J4bQnihIs1DAPaPoI3NRsUrLXCnalrIwm2IteZ0w130lWVDAPaPutDybBX5dHxPwI+XRhjY6mbxOOKQnCtIs9MA9o+60PNtRtevH9BCyKboUCyDDAQXcM+oOwplG1RNjvVoDfyFkU4TQyRAShxaKh9T5yGwKit350atqfUz3bcZmGqbOZGFxCTtm99N7Jt4RnIB/eu4IHnr6FayoYlQEN7//Utw1vWXNfgyYpdNWUCyEbApTJwP469mT4SaoFXk+PXcEf/LN76/Z/utXb1wl4smAGdAXC5/zgYcB3zvVtO9NEq6kRNqgEyvyPPT0K8btcQEPsaDRMOB7NkX86cQ0EvfJsyckqCDmiuFpIbk9hIAZ8ZPpbZN4amaXsX67T549IUGNwEdFUkV8VGTV6zYCZkXtAd/thGEnBM+ekKBG4De//1Kr7U2XOC2aPxx6vvEwrHgTWk0VMpzkBjFF5FIAXwZwEfpr8d6nqr8vIhcA2AtgE4CXANyoqiey3qtqEBPwMwtlx+z+1BG/KeBVdH+fYICYkOapEsQ8BeA2Vf2WiPwcgIMi8nUAvwXgCVWdFZEZADMAfsdlo9O4a3pLqmC3SVHPPWSPngFiQvwhV8BV9RiAY4OffyoizwOYBPAxAB8Y7PYAgP+BBgTchqbrbhT13EOY1GIi5M6nSzCGQoCCQUwR2QRgG4CnAVw0EHcA+CH6Fkva3+wGsBsANm7cWLqhWSS/zG/+v2bLoxYNeIUcIKtjXU8KUTFCKQxG6sc6iCki5wHYB+BWVf1J/HfaN9JTzXRVvU9Vp1R1asOGDZUam0ZaQHBxaTl137pGiUUDXiEHyFwGiH0N5voepGXNFhJhNQIXkR764v2gqj4y2PyaiFysqsdE5GIAr9fVyCzaKo+apOgkFd8ntZhwORXfRz89hNEtbSwSkSvgIiIA7gfwvKp+LvarRwHcAmB28P9Xa2lhDm2VRx1mXHU+PgqRj51KEpONNSKCzTOP0YoaImwslB0AfgPALhE5PPj3YfSF+5+IyHcBfGjwunFMo+r14/WWRyXV8XG9x6xiVr6QZmMB/RnJPllRpH5sslC+AUAMv/6g2+YUxxQQvOO68uVR2w6stX38LFy2Le3aCdot32o727dNkjbWSEqbfXtqIPUQ1FT6NFyXR23bA237+Fm4bluyeJTgnUh4W+dtW2+nbeI21uaZx1L3oSfefYKaSm8iKkD04uy1eGpmV6Ubvu0If9vHz6KOtsWLRyUlso3zNhWxMm33AR+tKNIMnRBwl7QdWGv7+FnU2TZfznvnFRvW+IW+B8Cbrv1D/CF4C6UqSU93YryHEyfX5pE3NZrxeZZmnW3z4bznDi1g38GFVU8CAuCG7X6nfLa1yhJpn6EegadNJPnZW6fQG109BmtyNOPzaCqtbfGgY5WsBx/OO80iUgAHjh5vrA1lcWkjknAY6hF42g27fFoxMdbDuWeva2U04/Noqs6gow/n7YuNQ4gtQa2JWZWkXWLK7RUAL85e22zjHNJEGqLvJXHLfAa+nxMZXkzlZIfGQkmzS0yZvT74zWVpqr6Iz6PVsp+BDzYOIUUYGgE3+ZuhZRzk0VQaos+pa2U/g5CLjJHhZGg8cNPIUNG/UX3zm8tiOk/Xsxt9Lolb5ekg1CJjZDgZGgE3ed5d8zezvH2Xsxt9CDqa8CElkZAm8F7AbYNRefv5PGJ0Sdp5xnFZI8PX0eqwXGtCvBZw29obpv3mX34DB44ePyPqN2yfXPW6iRFj04Wpkql+afgQaKwTn58OCHGJ12mEtmldpv3iecpA86unt72Ce91pcS47p7YrMLZ9fEKyCDKN0DYYlRWgjFMlG6PMMlttF6aqMy3OZbpi20urtX18QsritYDbpqoVCU6VsQ/K3uBt50rXmRbnsnNy3dEV7Wzb7mgJKYvXHrhtMMq0MECaOVQmE6HsMls+ZEPUFWh02TlVfa+4/XH+WA9vvn0Kyyv9q2+TedN2R0tIWbwegduOINP2+/jVG53ZB3m51aYRno8z+1ytuO5yIk+V90o+HS0uLZ8R74i80bTPk5IIycLrEThgP4JM22/qsgucBKbK5lb7lg3hckUdl6l6Vd4r7ekojazRNNMOSah4L+BVcGUfVMmt9ilX2uWK6y47pyrvZWtzZI2mfetoCbGl0wLuiq7kVrv2el12TmXfK+vpKMJmNO1TR0uILV574D4RX7sxjRD80qpeswvv3DVpcYbeiGD9eI8FqUjn4Qi8ICH7pWXb7no1epf4YH9wEhBpi04IeJMzApsQjLoEoWzbXXrnddCm/eFz55aEHU338HoqvQ0up6u3PfW9TBuauCk3zzyWmlMf+spFLghlFR8fvtukPEFOpbfBxSy6yN+9de/h1mfkFTmfpqaAM0/aTCiTgDjbtJsEL+AuZvFFIlj0GC6JOhGbLJemO5ymJiT5GijNIpTOLZSOhhQjeAGvegPZTASp+2a06USiNrTR4TSx1FiZpwkfBN/H2bZphNLRkGIEH8SsmhWSJ3ZjvVHsvGIDdszur81nzutE4ufTVodTd6CwaKDUl+BhVmDYp6BhyNlTxEyugIvIFwF8BMDrqvqewbY7AfwzAMcHu/0bVf3zuhqZRdWskKyJIJMTY9h5xQbsO7hQq1BkdSKTifOx6XBCvCmLPuL7lBmT1rn50sHE2whwtmnXsBmBfwnAHwD4cmL7var6e85bVIKs0WHZpdYii2DH7P7ahaLIep3nj/WwuLSc+j5JsU/Dp1FhnKKVG333dH3qYCI427R75HrgqvokgDcaaItzbHzVPH83q4iVK3ZesQGS2JY2kp47tIA33z615u97I4LP37QVT83syhVvXxcuKOIlzx1awIgkP7E+vni6vncwpBtU8cD/uYj8JoB5ALep6glHbXKG7Sgoa2QyKoKVlFz5UYOAxLEZ7c4dWsC+gwur8qwFwA3b17bpnsdfWFMqFQDOO2ed1cjKx1FhnLPXjZxp3/rxHu647iqjNZF2TXyyj3yoBU+6T9kslC8A+PsAtgI4BuCzph1FZLeIzIvI/PHjx0271YKLUVCaUGRtj0gb7e7ZexibEhkTaaKqAA4cXftZmdq9eDLdUrH9+7QUxSYzO6LPKm4NvbV8OnVfUxB3VMSrSSmhZKeQsCkl4Kr6mqquqOppAH8I4H0Z+96nqlOqOrVhw4ay7SyFi9QpU/Eq0/YIkzADq62LIp1M1WJUebZDWxaL6cngtoefWdORmD6v06reiDfQTOolIaUEXEQujr38FQDPummOW1yMgsq+R94oP7Iuiohy2bbY2g5tzdYzfVYrqms6kpDymaMKli/OXpsbnyCkDLkCLiIPAfhfAC4XkVdF5BMAfldEjojItwHsBLCn5naWwsUoKO09btg+iXsefyHTZrARlB8sLhUS5bLnY2s7tBV4s/msoo6E1gQh75AbxFTVm1M2319DWwphmw5nClAWSaeLv4dtfm/eKj5AX7iK5ueWSQWztR3aCrzZfFZA/zyYz0zIOwQ5E7PqJIkqf18ksyXaf2FxCQKsyjSJjxrrzs+1Fea2ZuslRXnEkPkTtZf5zIT0CbIWSlWvtsrfF7EZIg/0pdlrce9NW1sLaNnaDm0G3uJ+8WdvfC9tEkIsCHIEXtWrrfL3ZW2GNkeNRWwHH0a3tEkIsSNIAa/q1Vb5+1CLApUR5jan3fvQkRDiO0FaKFUzEdL+XgBs+vmx3Eksw5Lf6/O0e1f4UI6WkCoEu6Ra1dHhp+eO4MFvfj91qbCIYV5yyselwlyvfcolxkgomJZUC9JCAao/Yh84ejxTvIF+YPPWvYfP5B/bZrh0wbv1rRiT6/KsvteFIcSGIC0UFxSpJmhrH3TJdvBtxqPrWaK+dVCElCHYEXhVTFUGTdiMzpoc1dU10o/eNy93vWlcC64pkD0x3qt19aWqdOUJj7ih8wJu+sIXEe+IPLFoalRX12ovyfdV4IyI2ywWUSeuZ4mmZRP1RgU/e+sUTgyqO7a9ik4S31b5Ie3TaQvFZGl8eu7ImgUUIrLqfOeJhen3IyJObZS6ik6ZKihGgcuqnUOVjA/bzCPb46RlE5171josn17dsTdRzMuWtoqNEX/p9Ajc9IV/6OlXUgOYAuCzN74XAErleptqeqyoFh4pZT0q1zXSr+t9XYwcbSb3FD1OMhC+eeax1GP74ovTtw+TOm2vTgt4VpnSNBSrb/SiH3r0+9sefmbNMYp44XlCVMVOyPoy1VXMylVsIC/zqOpxfF9Fx/f2kbXUbXt12kIxfbFNNkl8kYaytZynt03itKGDWFhcsnq8zxKiuUMLOJmyLqbE3t/0vnlZMlk2RRULpKmRY9Xj+F6q1vf2kbXUbXt1WsBNX/ib339prTeCqeOIRDYvxdAkONHfnEhZQi1ttZ8keV8m0yxTAJXSI5tKSax6HN9n2frePrKWugcvnbZQsnzTqcsucOpLxa2J88d66I3KqgWIkyl5QF88P/Nnz605rulReVQkt2Z29L5ptoHNlynNptgxu7+SNdFU/RgXx/G9Bovv7SOrqdv26qyAJ73ee2/aar0SfZljxYVjcWkZvRHB+vEeFk8uGy8iAJw4uYy5Qwu5i0GM9UatxDvCtKZmmS9T1hOBTc50U9UFWcWwPph/Xo66By/B1kLJIq3OhQD4+NUbcdf0ltLvafoC29QNMe0T3y9+jPGzRvHm2++0/9yzRtEbHVm1cnsWaTVLitT/iLfFtMBC2kSfJh7pKSbNwrox1XDxfe1cLZQsTPnMD37z+5i67AJMb5ss9KHmRZJNwhwfud5+zeW4de9h437JY8TFO3o9OnIavRFZlavcGxFAsMquyVpTE8gfoSbbYiPeQL21REwzRDmZpX5YN6YaddpenRRw0yO/AmcCdlmCnBT3k2+fygz+pYkZsNqamN42iTsffS51BH3JxJhx4eE4K6cVf2e8h/Gz1q0SYMDtmppZiyCfVs20hOrISU6bIRqHYlIvzD/3l04KeJ7A5GVjJMXdxMLgvUyTgqL0u6zgZjRa3mMYnSdZPLmMQ//uF9dsd7VYw9yhBeM5n1bFi7PXAjBbQnXkJNt0bhST+mD+ub90Mo3w9msuN06Vv2RiLDMo95k/e846WDgqkjnaB1an3y0uLQMKrB/vrUkDK7KaUFWySgxETyJ5x955xYbUfUzbq2C71B2pB+af+0snBXx62yQ+fvXGNSIefemybva0HGsTKwM7IY1Jgy2yfFoxfta6NROE0m6SJL1RcXLTZJUYMHVeyRv2wNHjqfuZtlchT5wpJvXC/HN/6aSFAgB3TW/JzPVOq1lSlKhCnylNyGSLmFawB3AmUDciQLyu0vrxHu647ionueomiySrQmPyhm3SF037jH2pkjgsMP/cTzor4FlEX0RTVogN0Wg4K7PDJJamEaWpcxnrjToR77xOy1QjfXJizHqyUR1WRqj53Ux3JHXTCQFPu1GA7EyTLIGdGOsBQHbOdUznTKOTMkn8daVs5QUCx3qjuGH7JPYdXLBqb1OzKyNCGwGydjdpguA9cFNALi0YmSwiYwrO3PnRq3Du2dl92/JpzS1IY+MdJotE2aTnlSkslWVtRO26a3rLqvauH+/h7HUj2LP38Jrj0BfNhrW7SRMEPwI33Sim0WYkZNGofWl55Yx1EPdTbdL6bPzerJFj2igtL6e87MjOZHnEZ2zGn2Qmxnv42VunzkwaSjuO6dyKTpLqos3A3GnSBMGPwIveEJdMjK0atQP94J2gnwIXr41t815VMM0YNWXPmP5maXkFtz38TOZIPC8VLPkkc+LkcqnVaYos7NylRaCT+LYoNOkmwQu46YaYGOsZBStrqn1Wbey096pCVg65yZrIWqQiS/zyLA+byTJZx48oYh102WZg7jRpglwLRUS+COAjAF5X1fcMtl0AYC+ATQBeAnCjqp6or5lmTMG0Oz96FYD0zAWTPRJNtY9bA3FLQRX48dKys0f988d6qYHSNFtjz97DuGRizPg3QH6wM8vOsX2SKVu5MG17l22GUDNnSFjYeOBfAvAHAL4c2zYD4AlVnRWRmcHr33HfvHyybhTTaNS2lkedmQ9zhxbwZsrKOr0RWWNrxP3u3qisKWgVp6z4ZX0mETYjyCLphV2foh1a5gwJj1wLRVWfBPBGYvPHADww+PkBANNum1WMtOXPsvzVvKn2TXDP4y+sqokScd456zJtjeUVxXnnrDMuC1e2/XmW0aiIVZZJEeuANgMh1SibhXKRqh4b/PxDABc5ao8zsoJ9UdAySR3iYcqyMI2UF2NT+bP2ufemrU7zsPMmN62orrJyyizekPZZ3H39FtoMhJSkchqhqqqIGOdgi8huALsBYOPGjVUPB8Au9SxvRfq0Bp+9zm1MNyvlb2K8l1p3JT6CzrIYitT2LlJq1jS5KVrPM3keJhHPqzEevcfd129Zs/AEIcSOsor1mohcDACD/1837aiq96nqlKpObdhQvVKdbepZGSthcWm5UBpb3oQa01PAnY8+h5+9leJ/J4pV5VkMadZRsn1F0/TSjpm1eIMtXc44IaQtygr4owBuGfx8C4CvummOmUgsb9172EoIbKr7pWErKjbiaLRAltbmWAPAuWetWyXCVWc7lhHNtGOaHq+KBEy7nHFSlTIzawkB7NIIHwLwAQAXisirAO4AMAvgYRH5BICXAdxYZyNtCjElhSBpMRRZ+dNGVGxqlthkdsT5cUp6YJVMhrKimTymi8Ubup5xYiLPwmLNFFIFmyyUm1X1YlXtqeq7VPV+Vf2/qvpBVX23qn5IVZNZKk6xmWSSJgRxi2H9eM/6eDaiYiOOJgvE1BbXYuZqNqCLbJFhzDixeUqjtUSqEMRMzLwRo40Q3HHdVeiNmpIHi70XYCeOJgvkjuuuakTMXImmi8JVw1j8ykacaS2RKgRRzCrLirAt6G/K2ph/+Q089PQrWFHFqAhu2G5nWdiWU43bEcn1Mc/pjWDxpLuZnUlczgZ0MSll2Ca22IjzsFpLxA1BCLhJLMuMApP+476DC2dSC1dUse/gAqYuu6B0h2BbeXBxaRljvVHce9PWzNS/KlP4u1rpLxRsxLnpuupNwu9f/YhmLKPlmqmpKZ2fny/1t3V8GUzBuXgtElfYHisvYGvbcaW9T5lOzyXDdkPbXoMufi4+fv9CRkQOqupUcnsQI3CgnsfvpvzHuUMLVrVXgPyAre3qPHWt7FOWYcy2sH1K66K15Nv3r6sEI+B10IT/GAlXVhvi2HQeVfZpKzg2rDd0F8XZBt++f10liCyUumgitS1rRB0dKz6RY8RQpCpOlcUm2gqO8YYeLnz7/nWVoRbwJlLbsgTq7uu3AABu/9NnzuQKp60KH8e2g/Et75o39HDh2/evqwy1hQLU/4ibtRbl9LZJbP3MX6ZOq4/G4WWzUHxbUKDL2RZkLb59/7rK0At43eQJl2l1HQXw0uy1lY7tk//KG3r48On711Uo4AWxSflK7nPD9kkcOHp86IWLNzQhbqGAF8AmFS5tn30HF4ze+npDXfAitVsIIcPJUAcxi2JT26JocaK0Gi29UcEd113lqNWEkK7CEXgBbFLhiqbL1ekNl7F7mrZ32j5+6PDzG24o4AWwmfhTZnJQHd5wWbunydmRbR8/dPj5EVooBbDJbfUl/7UOu6eNNprgKjbtXz/SPhyBF8DG7ihiidT5+FuH3eOassfnyLNP29ePtA8FvCA2dofNPnkiVFXc67J7XFL2+MNaVyVJ29ePtA8tlJYwidBtDz+DTTOPYc/ew4VWk08Sgt1T9vimEWaR9Ue7QNvXj7QPBbwlTCIU1UJJTq4v6m3a1Hlpe5mzssc3jTAFGCovvO3rR9onmAUduoZpgYcsBMCLFafXd4G5QwvYs/fwmk4OqGcxDkLaxrSgA0fgLZH2+JsHvc0+09smU8UbYACPDBcU8JZIPv6O5tQBp7e5mkmWpyWEWShtklyxPlm1UND3wicbnp0ZAixPSwgF3BuaKLfapfxplqclJNAgZldGkU1jCpwy8EeI3wS/Kn1El0aRTdOFmXvsvAl5h+CCmKz/UJ4m16Wso1ZJ1HlXmeBESJcITsDrGEWGVBipSlubmrlXl9Cy8yZkNcEJuOtRZEijuqptbWrmXl1C2wULiBCXVPLAReQlAD8FsALgVJrJ7hrX6WMhFUZy0dYm1qWsS2hZvImQ1bgYge9U1a1NiDfgfhQZ0qgulLbW5bWzeBMhqwkmC6Wu7IOQRnWhtLWuSTbM/SZkNVUFXAH8pYgogP+iqvcldxCR3QB2A8DGjRtLHaTO1MGQZvSF0tY6hbYJC4iQUKg0kUdEJlV1QUT+LoCvA/gXqvqkaf+yE3nqnoASUm5xSG0lhLihlok8qrow+P91EfnvAN4HwCjgZanb+w1pVBdSWwkh9VI6iCki54rIz0U/A/hFAM+6alicJiegEEJIKFTJQrkIwDdE5BkAfw3gMVX9CzfNWg2zDwghZC2lLRRV/VsA73XYFiPMPiCEkLUEk0ZI75cQQlYT3FR6QgghfSjghBASKBRwQggJFAo4IYQESjBBzDJw1iIhpMt0VsC59BohpOt01kLh6i2EkK7TWQEPpXY2IYSUpbMCzvophJCu01kBZ/0UQkjX6WwQk/VTCCFdp7MCDrB+CiGk23TWQiGEkK5DASeEkEChgBNCSKBQwAkhJFAo4IQQEiidzkLJg8WuCCEhM7QCzmJXhJDQGVoLhcWuCCGhM7QCzmJXhJDQGVoBZ7ErQkjoDK2As9gVISR0hjaIyWJXhJDQGVoBB1jsihASNkNroRBCSOhQwAkhJFAo4IQQEigUcEIICRQKOCGEBIqoanMHEzkO4OUSf3ohgB85bo4PdPG8unhOAM8rJLp4Tpep6obkxkYFvCwiMq+qU223wzVdPK8unhPA8wqJLp6TCVoohBASKBRwQggJlFAE/L62G1ATXTyvLp4TwPMKiS6eUypBeOCEEELWEsoInBBCSAIKOCGEBIr3Ai4ivyQiL4jI90Rkpu32lEFELhWRAyLyHRF5TkQ+Odh+gYh8XUS+O/h/fdttLYOIjIrIIRH52uD1ZhF5enDN9orIWW23sQgiMiEiXxGRoyLyvIj8wy5cKxHZM/j+PSsiD4nIOSFeKxH5ooi8LiLPxralXh/p858G5/dtEfmF9lruHq8FXERGAfxnAL8M4EoAN4vIle22qhSnANymqlcCuBrAbw/OYwbAE6r6bgBPDF6HyCcBPB97/R8B3Kuq/wDACQCfaKVV5fl9AH+hqlcAeC/65xb0tRKRSQD/EsCUqr4HwCiAX0OY1+pLAH4psc10fX4ZwLsH/3YD+EJDbWwErwUcwPsAfE9V/1ZV3wbw3wB8rOU2FUZVj6nqtwY//xR9QZhE/1weGOz2AIDpVhpYARF5F4BrAfzR4LUA2AXgK4NdgjovETkfwD8GcD8AqOrbqrqIDlwr9Ov/j4nIOgDjAI4hwGulqk8CeCOx2XR9Pgbgy9rnmwAmROTiRhraAL4L+CSAV2KvXx1sCxYR2QRgG4CnAVykqscGv/ohgIvaalcFPg/gXwM4PXj98wAWVfXU4HVo12wzgOMA/uvAFvojETkXgV8rVV0A8HsAvo++cP8YwEGEfa3imK5P5zQkju8C3ilE5DwA+wDcqqo/if9O+/mcQeV0ishHALyuqgfbbotD1gH4BQBfUNVtAN5Ewi4J9FqtR380uhnAJQDOxVobohOEeH3K4ruALwC4NPb6XYNtwSEiPfTF+0FVfWSw+bXocW7w/+ttta8kOwB8VEReQt/e2oW+fzwxeEwHwrtmrwJ4VVWfHrz+CvqCHvq1+hCAF1X1uKouA3gE/esX8rWKY7o+ndGQNHwX8P8N4N2DSPlZ6AddHm25TYUZ+ML3A3heVT8X+9WjAG4Z/HwLgK823bYqqOqnVPVdqroJ/WuzX1U/DuAAgF8d7BbUeanqDwG8IiKXDzZ9EMB3EPi1Qt86uVpExgffx+i8gr1WCUzX51EAvznIRrkawI9jVkv4qKrX/wB8GMD/AfA3AP5t2+0peQ7/CP1Hum8DODz492H0/eInAHwXwF8BuKDttlY4xw8A+Nrg578H4K8BfA/AnwI4u+32FTyXrQDmB9drDsD6LlwrAJ8BcBTAswD+GMDZIV4rAA+h7+Mvo//E9AnT9QEg6Gey/Q2AI+hn4bR+Dq7+cSo9IYQEiu8WCiGEEAMUcEIICRQKOCGEBAoFnBBCAoUCTgghgUIBJ4SQQKGAE0JIoPx/WpR66BTAR70AAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "plt.scatter(data.newspaper,data.sales)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "107f970d",
   "metadata": {},
   "outputs": [],
   "source": [
    "x = data.iloc[:,1:-1]\n",
    "y = data.iloc[:-1]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c640cae6",
   "metadata": {},
   "outputs": [],
   "source": [
    "model = tf.keras.Sequential([tf.keras.layers.Dense(10,input_shape=(3,),activation=\"relu\"),\n",
    "                            tf.keras.layers.Dense(1)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "ae7c3f7f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_1\"\n",
      "_________________________________________________________________\n",
      "Layer (type)                 Output Shape              Param #   \n",
      "=================================================================\n",
      "dense_2 (Dense)              (None, 10)                40        \n",
      "_________________________________________________________________\n",
      "dense_3 (Dense)              (None, 1)                 11        \n",
      "=================================================================\n",
      "Total params: 51\n",
      "Trainable params: 51\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "c22fea50",
   "metadata": {},
   "outputs": [],
   "source": [
    "model.compile(optimizer=\"adam\",\n",
    "            loss=\"mse\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "709ed250",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Falling back from v2 loop because of error: Failed to find data adapter that can handle input: <class 'pandas.core.frame.DataFrame'>, <class 'NoneType'>\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n",
      "ERROR:root:Internal Python error in the inspect module.\n",
      "Below is the traceback from this internal error.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_8547/4096229100.py\", line 1, in <module>\n",
      "    model.fit(x,y,epochs=100)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 728, in fit\n",
      "    use_multiprocessing=use_multiprocessing)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py\", line 642, in fit\n",
      "    shuffle=shuffle)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 2534, in _standardize_user_data\n",
      "    training_utils.check_array_lengths(x, y, sample_weights)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py\", line 677, in check_array_lengths\n",
      "    'and ' + str(list(set_y)[0]) + ' target samples.')\n",
      "ValueError: Input arrays should have the same number of samples as target arrays. Found 200 input samples and 199 target samples.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_8547/4096229100.py\", line 1, in <module>\n",
      "    model.fit(x,y,epochs=100)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 728, in fit\n",
      "    use_multiprocessing=use_multiprocessing)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py\", line 642, in fit\n",
      "    shuffle=shuffle)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 2534, in _standardize_user_data\n",
      "    training_utils.check_array_lengths(x, y, sample_weights)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py\", line 677, in check_array_lengths\n",
      "    'and ' + str(list(set_y)[0]) + ' target samples.')\n",
      "ValueError: Input arrays should have the same number of samples as target arrays. Found 200 input samples and 199 target samples.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_8547/4096229100.py\", line 1, in <module>\n",
      "    model.fit(x,y,epochs=100)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 728, in fit\n",
      "    use_multiprocessing=use_multiprocessing)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py\", line 642, in fit\n",
      "    shuffle=shuffle)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py\", line 2534, in _standardize_user_data\n",
      "    training_utils.check_array_lengths(x, y, sample_weights)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_utils.py\", line 677, in check_array_lengths\n",
      "    'and ' + str(list(set_y)[0]) + ' target samples.')\n",
      "ValueError: Input arrays should have the same number of samples as target arrays. Found 200 input samples and 199 target samples.\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'ValueError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3461, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1125, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3173, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 3383, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2067, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1368, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1268, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1143, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/interactiveshell.py\", line 2064, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 1101, in get_records\n",
      "    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 248, in wrapped\n",
      "    return f(*args, **kwargs)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n",
      "    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 1502, in getinnerframes\n",
      "    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 1460, in getframeinfo\n",
      "    filename = getsourcefile(frame) or getfile(frame)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 696, in getsourcefile\n",
      "    if getattr(getmodule(object, filename), '__loader__', None) is not None:\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/inspect.py\", line 733, in getmodule\n",
      "    if ismodule(module) and hasattr(module, '__file__'):\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow/__init__.py\", line 50, in __getattr__\n",
      "    module = self._load()\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/tensorflow/__init__.py\", line 44, in _load\n",
      "    module = _importlib.import_module(self.__name__)\n",
      "  File \"/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/importlib/__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 965, in _find_and_load_unlocked\n",
      "ModuleNotFoundError: No module named 'tensorflow_core.estimator'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR! Session/line number was not unique in database. History logging moved to new session 10\n"
     ]
    }
   ],
   "source": [
    "model.fit(x,y,epochs=100)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad46efa9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
